version: 1.0.{build}-{branch}
build:
  verbosity: minimal

environment:
  APPVEYOR_TOKEN:
    secure: 7hdKHlNyvrMs7WCTMr2Eaw1nb25MxQTABu/Nux7gyWM=

skip_commits:
  files:
    - appveyor_2.yml

image: Ubuntu2004

build_script:
- ps: echo "Build script goes here"

on_success:
- ps: echo "Success"
- ps: >-
    $apiUrl = 'https://ci.appveyor.com/api'
    $token = $Env:APPVEYOR_TOKEN
    $headers = @{
      "Authorization" = "$token"
      "Content-type" = "application/json"
    }
    $accountName = 'Yuriy-Pelekh'
    $projectSlug = 'idf0-2'
    $branch = $Env:APPVEYOR_REPO_BRANCH
    $pullRequestHeadBranch = $Env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
    $pullRequestId = $Env:APPVEYOR_PULL_REQUEST_NUMBER

    echo "branch = $branch pullRequestHeadBranch = $pullRequestHeadBranch pullRequestId = $pullRequestId"
    
    $body = @{
      accountName = "$accountName"
      projectSlug = "$projectSlug"
      branch = "$branch"
      pullRequestHeadBranch = "$pullRequestHeadBranch"
      pullRequestId = "pullRequestId"
    }
    $bodyAsJson = $body | ConvertTo-json
    Invoke-Restmethod -uri "$apiUrl/builds" -Headers $headers -Method "Post" -Body $bodyAsJson

on_failure:
- ps: echo "Fail"

#notifications:
#- provider: Webhook
#  url: https://ci.appveyor.com/api/builds
#  method: POST
#  headers:
#    Authorization:
#      secure: 7hdKHlNyvrMs7WCTMr2Eaw1nb25MxQTABu/Nux7gyWM=
#  body: >-
#    {
#      accountName: "Yuriy-Pelekh",
#      projectSlug: "idf0-2",
#      branch: "{{branch}}",
#      pullRequestHeadBranch: "{{pullRequestHeadBranch}}",
#      pullRequestId: "{{pullRequestId}}"
#    }
#  on_build_success: true
#  on_build_failure: false
#  on_build_status_changed: false
